spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/reviews_db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jwt:
    secret: dljfjaldkfjaksldfjaldkfjlkadsfjakslfjafejfopajdiofjaiodfdlksfjakldfjakldsf

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

naver:
  url:
    search:
      local: "https://openapi.naver.com/v1/search/local.json"
      image: "https://openapi.naver.com/v1/search/image"
  client:
    id: 942xEdx8DRSPviV0bqW4
    secret: fQhY5rNaI5


logging:
  level:
    root: INFO # 전체 로그 레벨 설정
    org:
      springframework:
        security: DEBUG # Spring Security 로그 레벨 설정

      hibernate:
        SQL: DEBUG # Hibernate SQL 로그 레벨 설정
