spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/reviews_db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jwt:
    secret: dljfjaldkfjaksldfjaldkfjlkadsfjakslfjafejfopajdiofjaiodfdlksfjakldfjakldsf

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    root: INFO # 전체 로그 레벨 설정
    org:
      springframework:
        security: DEBUG # Spring Security 로그 레벨 설정

      hibernate:
        SQL: DEBUG # Hibernate SQL 로그 레벨 설정
